from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any
from datetime import datetime

class IncidentEvent(BaseModel):
    model_config = ConfigDict(extra="allow")

    incident_id: str = Field(..., description="Unique identifier for the generated incident")
    affected_nodes: List[str] = Field(..., description="List of node_ids impacted by the failure")
    severity: str = Field(..., description="Severity level (e.g., 'high', 'critical')")
    raw_logs: str = Field(..., description="String block of the captured error logs")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Time the incident was registered")
    status: str = Field(default="active", description="Resolution status (active, mitigating, resolved)")
    recommended_config: Optional[Dict[str, Any]] = Field(default=None, description="Optimal patch config generated by the Pareto optimizer")
